{
    "name": "MHD Contract",
    "version": "18.0.0.1.0",
    "author": "NOS ERP Consulting",
    "license": "OEEL-1",
    "depends": [
        "hr_contract",
    ],
    "website": "https://www.nostech.vn",
    "maintainers": ["tinnguyen189atnos"],
    "data": [
        "data/report_paperformat.xml",
        "views/hr_contract_views.xml",
        "views/hr_employee_views.xml",
        "report/hr_contract_collaborator.xml",
        "report/hr_contract_collaborator_1.xml",
        "report/hr_contract_collaborator_salary.xml",
        "report/report_indefinite_employment_contract.xml",
        "report/report_term_employment_contract.xml",
        "report/report_probation_contract.xml",
        "report/report_intern_agreement.xml",
    ],
    "application": True,
    "installable": True,
}
