{
    "name": "Metatech Human Resources",
    "version": "1.0",
    "author": "Metatech Solutions JSC",
    "website": "http://metatechsolutions.vn/",
    "depends": [
        "hr",
        "hr_holidays",
        "hr_payroll_community",
        "hr_contract",
        "hr_skills",
        "hr_attendance",
        "hr_recruitment",
        "website_slides",
        "website_profile",
        "survey",
        "purchase",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/contract_sequence.xml",
        # "data/hr.ethnicity.csv",
        "data/hr_resume_data.xml",
        "data/ir_rule.xml",
        "views/hr_views.xml",
        "views/hr_poliy_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_salary_type_views.xml",
        "views/hr_clothing_code_views.xml",
        "views/res_company_views.xml",
        "views/hr_ethnicity_views.xml",
        "views/hr_applicant_views.xml",
        "views/slide_channel.xml",
        "views/website_profile.xml",
        "views/survey_templates.xml",
        "views/slide_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "metatech_hr/static/src/fields/**/*",
        ],
        "web.assets_frontend": [
            "metatech_hr/static/src/scss/website_profile.scss",
            "metatech_hr/static/src/scss/disable_link.scss",
            "metatech_hr/static/src/js/slide_sidebar.js",
        ],
        'web.report_assets_common': [
            "metatech_hr/static/src/scss/survey_report.scss",
        ],
    },
    "license": "OEEL-1",
}
