from . import sale_channel
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import stock_warehouse
from . import analytic_account
from . import crm_team
from . import stock_picking
from . import helpdesk_ticket
from . import share_func
from . import hr_contract
from . import ir_attachment
from . import hr_application
from . import account_move
from . import purchase_order
from . import approval
from . import repair_order
from . import stock_location
from . import res_company
from . import res_config_setting
from . import product
from . import stock_quant
from . import sale_report
from . import account_invoice_report
from . import brand_name
from . import rating_rating
from . import coupon
from . import coupon_program
from . import stock_move
from . import stock_rule
from . import res_size
from . import partner_hobby
from . import matter_concern
from . import repair_line
from . import repair_fee
from . import loyalty_program
from . import models
