from . import hr_dependent
from . import hr_employee
from . import hr_employee_public
from . import hr_ethnicity
from . import hr_policy
from . import hr_contract
from . import hr_salary_type
from . import hr_salary_type_line
from . import salary_type_tracking
from . import hr_clothing_code
from . import res_company
from . import hr_resume_line
from . import hr_resume_line_type
from . import hr_applicant
from . import slide_channel
from . import purchase_order
from . import ir_attachment