from . import sms_sms
from . import account_follow_up_report
from . import sms_brandname
from . import account_bank_statement
from . import brand_name
from . import zalo_oa
from . import helpdesk_ticket
from . import sale_order
from . import res_company
from . import res_config_setting
from . import ir_ui_view
from . import zns_template_val
from . import stock_picking
from . import coupon_program
from . import res_partner
