{
    "name": "Nguon Song Viet Customize",
    "version": "18.0.1.1.0",
    "category": "General",
    "author": "NOS ERP Consulting",
    "website": "https://www.nostech.vn",
    "license": "AGPL-3",
    "summary": """
Custom for Nguon Song Viet
        """,
    "depends": [
        "base",
        "product",
        "sale",
        "sale_stock",
        "account",
        "helpdesk",
        "hr",
        "hr_recruitment",
        "repair",
        "delivery",
        # "account_asset",
        "rating",
        "partner_address_vn_base",
        # 'colorized_tree_view',
        # 'sale_coupon',
        "stock",
        "purchase_stock",
        "common_connector_library",
        "approvals_pricelist",
        "phone_validation",
        "stock_account",
        "helpdesk_ticket_type",
        "helpdesk_stock",
        "base_vat",
    ],
    "data": [
        # # Views
        "security/mail_security.xml",
        "views/sale_channel_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_form.xml",
        "views/stock_warehouse_views.xml",
        # 'views/account_analytic_views.xml',
        # 'views/stock_warehouse_views.xml',
        "views/crm_team_views.xml",
        "views/crm_lead_views.xml",
        "views/product_views.xml",
        "views/stock_picking_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_application_views.xml",
        "views/account_move_views.xml",
        "views/purchase_order_views.xml",
        "views/repair_order_views.xml",
        "views/res_config_setting_views.xml",
        "views/res_loyalty_level_views.xml",
        "views/stock_move_line_views.xml",
        "views/stock_quant_views.xml",
        "views/brand_name_views.xml",
        "views/loyalty_program_views.xml",
        # 'views/coupon_program_views.xml',
        "views/product_size_views.xml",
        # 'views/mail_activity_views.xml',
        "views/partner_hobby_views.xml",
        "views/matter_concern_views.xml",
        "views/hr_employee_public_views.xml",
        # Menu
        "menu/channel_menu.xml",
        "menu/stock_menu.xml",
        "menu/sale_menu.xml",
        "menu/product_menu.xml",
        # Security
        "security/account_product_security.xml",
        "security/sale_security.xml",
        "security/stock_security.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        # Data
        "data/mail_data.xml",
        # TODO: check cron function
        "data/ir_cron.xml",
        # TODO: check server action function
        "data/server_action.xml",
        # Report
        "report/report_paper_format.xml",
        "report/report_account_statement.xml",
        "report/report_layout_template.xml",
        "report/report_picking_out_template.xml",
        "report/report_picking_in_template.xml",
        "report/report_sale_order_template.xml",
        "report/report_payment_receipt_templates.xml",
        "report/report_helpdesk_ticket_template.xml",
        "report/report_repair_order_template.xml",
        "report/report_purchase_order_template.xml",
        "report/product_failure_report_views.xml",  # TODO: check
        "report/report_sale_order_gymaster_template.xml",
        "report/report_deliveryslip.xml",
        "report/helpdesk_ticket_analysis_views.xml",
        "menu/helpdesk_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "assets": {
        "web.assets_backend": [
            "nsv_customize/static/src/js/*",
            "nsv_customize/static/src/xml/*",
        ],
    },
}
