{
    "name": "MISA AMIS Connector",
    "version": "18.0.1.0.0",
    "license": "OEEL-1",
    "summary": "Connect data with MISA AMIS",
    "website": "https://www.nostech.vn",
    "author": "NOS ERP Consulting",
    "depends": ["sale", "account", "accountant", "nsv_customize"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_server_action.xml",
        "data/misa_invoice_buyer_data.xml",
        "data/product_server_actions.xml",
        "data/ir_cron_product.xml",
        "wizard/inv_make_sa_vouchers_views.xml",
        "wizard/misa_push_wizard_views.xml",
        "wizard/misa_product_sync_wizard_views.xml",
        "views/account_account_views.xml",
        "views/account_analytic_account_views.xml",
        "views/misa_product_views.xml",
        "views/product_views.xml",
        "views/res_partner_views.xml",
        "views/misa_app_views.xml",
        "views/misa_sa_voucher_views.xml",
        "views/misa_menuitems.xml",
        # "views/sale_order_views.xml",
        "views/stock_location_views.xml",
        "views/account_move_views.xml",
    ],
    "installable": True,
}
